# Generated by Django 5.1.6 on 2025-02-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='category_images/'),
        ),
    ]
