# Generated by Django 5.1.6 on 2025-03-01 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_image_alter_postcategory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW_POST', 'View Post'), ('LIKE_POST', 'Like Post'), ('COMMENT', 'Comment'), ('REPLY', 'Reply'), ('SHARE_POST', 'Share Post'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ADMIN_LOGIN', 'Admin Login'), ('CREATE_POST', 'Create Post'), ('EDIT_POST', 'Edit Post'), ('DELETE_POST', 'Delete Post'), ('SUBSCRIBE_NEWSLETTER', 'Subscribe to Newsletter'), ('CONTACT_SUBMISSION', 'Contact Form Submission')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('time_spent', models.PositiveIntegerField(blank=True, help_text='Time spent in seconds', null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='home.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='home.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
